// AUTO-GENERATED by scripts/generate_scored_yara.py -- DO NOT EDIT BY HAND
// Source: yara_rules/Yara-Rules-Repo/utils/base64.yar (Yara-Rules project, https://github.com/Yara-Rules/rules)
// Risk scores per .claude/criterioPuntuacionReglas.md (risk = 0.45*severity + 0.30*confidence + 0.25*exploitability)
// Generated: 2026-08-31T08:26:58.693710
// Contains only the 1 rule(s) present in yara_scores_output/yara_rule_scores.json

rule contains_base64 : Base64
{
    meta:
		severity_score = 25
		confidence_score = 30
		exploitability_score = 80
		risk_score = 40
		risk_justification = "Extractor de IOC generico: cualquier bloque de 4+ caracteres en alfabeto base64 dispara la regla (binarios, imagenes, fuentes, cualquier dato comprimido/codificado la contienen); util como building block para extraer un posible artefacto embebido, no es un veredicto por si mismo."
		finding_type = "malicious"
		needs_review = true
		needs_review_reason = "extractor de IOC generico: cualquier bloque de 4+ caracteres en alfabeto base64 dispara la regla (binarios, imagenes, fuentes, cualquier dato comprimido/codificado la contienen); util como building block para extraer un posible artefacto embebido, no es un veredicto por si mismo"
        author = "Jaume Martin"
        description = "This rule finds for base64 strings"
        version = "0.2"
        notes = "https://github.com/Yara-Rules/rules/issues/153"
    strings:
        $a = /([A-Za-z0-9+\/]{4}){3,}([A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?/
    condition:
        $a
}

