// AUTO-GENERATED by scripts/generate_scored_yara.py -- DO NOT EDIT BY HAND
// Source: yara_rules/Yara-Rules-Repo/utils/domain.yar (Yara-Rules project, https://github.com/Yara-Rules/rules)
// Risk scores per .claude/criterioPuntuacionReglas.md (risk = 0.45*severity + 0.30*confidence + 0.25*exploitability)
// Generated: 2026-08-28T10:31:17.386649
// Contains only the 1 rule(s) present in yara_scores_output/yara_rule_scores.json

rule domain {
    meta:
		severity_score = 25
		confidence_score = 30
		exploitability_score = 80
		risk_score = 40
		risk_justification = "Extractor de IOC generico: la regex no exige TLD valido ni contexto, matchea cualquier token con puntos/guiones (nombres de fichero, rutas, namespaces de codigo...); sirve para extraer un posible dominio, no prueba nada."
		finding_type = "malicious"
		needs_review = true
		needs_review_reason = "extractor de IOC generico: la regex no exige TLD valido ni contexto, matchea cualquier token con puntos/guiones (nombres de fichero, rutas, namespaces de codigo...); sirve para extraer un posible dominio, no prueba nada"
        author = "Antonio S. <asanchez@plutec.net>"
    strings:
        $domain_regex = /([\w\.-]+)/ wide ascii
    condition:
        $domain_regex
}

