// AUTO-GENERATED by scripts/generate_scored_yara.py -- DO NOT EDIT BY HAND
// Source: yara_rules/Yara-Rules-Repo/utils/magic.yar (Yara-Rules project, https://github.com/Yara-Rules/rules)
// Risk scores per .claude/criterioPuntuacionReglas.md (risk = 0.45*severity + 0.30*confidence + 0.25*exploitability)
// Generated: 2026-08-28T10:31:17.390621
// Contains only the 1 rule(s) present in yara_scores_output/yara_rule_scores.json

rule maldoc_OLE_file_magic_number : maldoc
{
    meta:
		severity_score = 25
		confidence_score = 30
		exploitability_score = 80
		risk_score = 40
		risk_justification = "Identifica el magic number del formato de fichero compuesto OLE (.doc/.xls/.ppt antiguos) -- cierto para el 100% de esos ficheros, sean o no maliciosos; sirve para enrutar la muestra a analisis de macros/streams OLE, no es un veredicto."
		finding_type = "malicious"
		needs_review = true
		needs_review_reason = "identifica el magic number del formato de fichero compuesto OLE (.doc/.xls/.ppt antiguos) -- cierto para el 100% de esos ficheros, sean o no maliciosos; sirve para enrutar la muestra a analisis de macros/streams OLE, no es un veredicto"
        author = "Didier Stevens (https://DidierStevens.com)"
    strings:
        $a = {D0 CF 11 E0}
    condition:
        $a
}

