// AUTO-GENERATED by scripts/generate_scored_yara.py -- DO NOT EDIT BY HAND
// Source: yara_rules/Yara-Rules-Repo/utils/url.yar (Yara-Rules project, https://github.com/Yara-Rules/rules)
// Risk scores per .claude/criterioPuntuacionReglas.md (risk = 0.45*severity + 0.30*confidence + 0.25*exploitability)
// Generated: 2026-08-28T10:31:17.404391
// Contains only the 1 rule(s) present in yara_scores_output/yara_rule_scores.json

rule url {
    meta:
		severity_score = 25
		confidence_score = 30
		exploitability_score = 80
		risk_score = 40
		risk_justification = "Extractor de IOC generico: cualquier 'http(s)://' seguido de texto dispara la regla, sin validar el dominio; util para extraer una posible URL, no prueba nada por si mismo."
		finding_type = "malicious"
		needs_review = true
		needs_review_reason = "extractor de IOC generico: cualquier 'http(s)://' seguido de texto dispara la regla, sin validar el dominio; util para extraer una posible URL, no prueba nada por si mismo"
        author = "Antonio S. <asanchez@plutec.net>"
    strings:
        $url_regex = /https?:\/\/([\w\.-]+)([\/\w \.-]*)/ wide ascii
    condition:
        $url_regex
}

