"""Add VCSConnection and MonitoredRepo

Revision ID: 532ab023f597
Revises: 599015186615
Create Date: 2026-08-12 09:59:06.673011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import watchgate


# revision identifiers, used by Alembic.
revision: str = '532ab023f597'
down_revision: Union[str, Sequence[str], None] = '599015186615'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vcs_connections',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('installation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('access_token', watchgate.db.crypto.EncryptedString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vcs_connections_org_id'), 'vcs_connections', ['org_id'], unique=False)
    op.create_table('monitored_repos',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vcs_connection_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('repo_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('monitor_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_scanned_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['vcs_connection_id'], ['vcs_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitored_repos_org_id'), 'monitored_repos', ['org_id'], unique=False)
    op.create_index(op.f('ix_monitored_repos_repo_path'), 'monitored_repos', ['repo_path'], unique=False)
    op.create_index(op.f('ix_monitored_repos_vcs_connection_id'), 'monitored_repos', ['vcs_connection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monitored_repos_vcs_connection_id'), table_name='monitored_repos')
    op.drop_index(op.f('ix_monitored_repos_repo_path'), table_name='monitored_repos')
    op.drop_index(op.f('ix_monitored_repos_org_id'), table_name='monitored_repos')
    op.drop_table('monitored_repos')
    op.drop_index(op.f('ix_vcs_connections_org_id'), table_name='vcs_connections')
    op.drop_table('vcs_connections')
    # ### end Alembic commands ###
