// AUTO-GENERATED by scripts/generate_scored_yara.py -- DO NOT EDIT BY HAND
// Source: yara_rules/Yara-Rules-Repo/webshells/WShell_Drupalgeddon2_icos.yar (Yara-Rules project, https://github.com/Yara-Rules/rules)
// Risk scores per .claude/criterioPuntuacionReglas.md (risk = 0.45*severity + 0.30*confidence + 0.25*exploitability)
// Generated: 2026-08-28T10:49:10.215820
// Contains only the 1 rule(s) present in yara_scores_output/yara_rule_scores.json

rule Dotico_PHP_webshell : webshell {
    meta:
		severity_score = 100
		confidence_score = 60
		exploitability_score = 80
		risk_score = 83
		risk_justification = "[.ico PHP webshell - file <eight-num-letter-chars>.ico] Web shell / backdoor signature -- indicates a deployed remote-code-execution capability if it matches. Confidence: mixed specificity literal(s) (min length 5); moderate FP risk. Triggers whenever the shell is invoked via a normal HTTP request to the deployed file -- no special condition needed."
		finding_type = "malicious"
        description = ".ico PHP webshell - file <eight-num-letter-chars>.ico"
        author = "Luis Fueris"
        reference = "https://rankinstudio.com/Drupal_ico_index_hack"
        date = "2019/12/04"
    strings:
        $php = "<?php" ascii
        $regexp = /basename\/\*[a-z0-9]{,6}\*\/\(\/\*[a-z0-9]{,5}\*\/trim\/\*[a-z0-9]{,5}\*\/\(\/\*[a-z0-9]{,5}\*\//
    condition:
        $php at 0 and $regexp and filesize > 70KB and filesize < 110KB
}

