// AUTO-GENERATED by scripts/generate_scored_yara.py -- DO NOT EDIT BY HAND
// Source: yara_rules/Yara-Rules-Repo/webshells/WShell_ASPXSpy.yar (Yara-Rules project, https://github.com/Yara-Rules/rules)
// Risk scores per .claude/criterioPuntuacionReglas.md (risk = 0.45*severity + 0.30*confidence + 0.25*exploitability)
// Generated: 2026-08-10T08:57:28.602852
// Contains only the 1 rule(s) present in yara_scores_output/yara_rule_scores.json

rule Backdoor_WebShell_asp : ASPXSpy
{
    meta:
		severity_score = 100
		confidence_score = 60
		exploitability_score = 80
		risk_score = 83
		risk_justification = "[Detect ASPXSpy] Web shell / backdoor signature -- indicates a deployed remote-code-execution capability if it matches. Confidence: mixed specificity literal(s) (min length 8); moderate FP risk. Triggers whenever the shell is invoked via a normal HTTP request to the deployed file -- no special condition needed."
		finding_type = "malicious"
    description= "Detect ASPXSpy"
    author = "xylitol@temari.fr"
    date = "2019-02-26"
    
    strings:
    $string1 = "CmdShell" wide ascii
    $string2 = "ADSViewer" wide ascii
    $string3 = "ASPXSpy.Bin" wide ascii
    $string4 = "PortScan" wide ascii
    $plugin = "Test.AspxSpyPlugins" wide ascii
 
    condition:
    3 of ($string*) or $plugin
}

