// AUTO-GENERATED by scripts/generate_scored_yara.py -- DO NOT EDIT BY HAND
// Source: yara_rules/Yara-Rules-Repo/webshells/Wshell_ChineseSpam.yar (Yara-Rules project, https://github.com/Yara-Rules/rules)
// Risk scores per .claude/criterioPuntuacionReglas.md (risk = 0.45*severity + 0.30*confidence + 0.25*exploitability)
// Generated: 2026-08-31T08:26:58.775894
// Contains only the 2 rule(s) present in yara_scores_output/yara_rule_scores.json

rule chinese_spam_spreader : webshell
{
    meta:
		severity_score = 100
		confidence_score = 100
		exploitability_score = 80
		risk_score = 95
		risk_justification = "[Catches chinese PHP spam files (autospreaders)] Web shell / backdoor signature -- indicates a deployed remote-code-execution capability if it matches. Confidence: requires 2 specific literal fragments to ALL match (min length 20); low FP risk. Triggers whenever the shell is invoked via a normal HTTP request to the deployed file -- no special condition needed."
		finding_type = "malicious"
        author      = "Vlad https://github.com/vlad-s"
        date        = "2016/07/18"
        description = "Catches chinese PHP spam files (autospreaders)"
    strings:
        $a = "User-Agent: aQ0O010O"
        $b = "<font color='red'><b>Connection Error!</b></font>"
        $c = /if ?\(\$_POST\[Submit\]\) ?{/
    condition:
        all of them
}

rule chinese_spam_echoer : webshell
{
    meta:
		severity_score = 100
		confidence_score = 100
		exploitability_score = 80
		risk_score = 95
		risk_justification = "[Catches chinese PHP spam files (printers)] Web shell / backdoor signature -- indicates a deployed remote-code-execution capability if it matches. Confidence: requires 4 specific literal fragments to ALL match (min length 12); low FP risk. Triggers whenever the shell is invoked via a normal HTTP request to the deployed file -- no special condition needed."
		finding_type = "malicious"
        author      = "Vlad https://github.com/vlad-s"
        date        = "2016/07/18"
        description = "Catches chinese PHP spam files (printers)"
    strings:
        $a = "set_time_limit(0)"
        $b = "date_default_timezone_set('PRC');"
        $c = "$Content_mb;"
        $d = "/index.php?host="
    condition:
        all of them
}

