// AUTO-GENERATED by scripts/generate_scored_yara.py -- DO NOT EDIT BY HAND
// Source: yara_rules/Yara-Rules-Repo/webshells/WShell_ChinaChopper.yar (Yara-Rules project, https://github.com/Yara-Rules/rules)
// Risk scores per .claude/criterioPuntuacionReglas.md (risk = 0.45*severity + 0.30*confidence + 0.25*exploitability)
// Generated: 2026-08-28T10:15:24.986312
// Contains only the 2 rule(s) present in yara_scores_output/yara_rule_scores.json

rule webshell_ChinaChopper_aspx
{
  meta:
		severity_score = 100
		confidence_score = 60
		exploitability_score = 80
		risk_score = 83
		risk_justification = "[Detect China Chopper ASPX webshell] Web shell / backdoor signature -- indicates a deployed remote-code-execution capability if it matches. Confidence: regex/byte-pattern only (not individually inspected); medium confidence. Triggers whenever the shell is invoked via a normal HTTP request to the deployed file -- no special condition needed."
		finding_type = "malicious"
    author      = "Ryan Boyle randomrhythm@rhythmengineering.com"
    date        = "2020/10/28"
    description = "Detect China Chopper ASPX webshell"
    reference1  = "https://www.fireeye.com/blog/threat-research/2013/08/breaking-down-the-china-chopper-web-shell-part-i.html"
    filetype    = "aspx"
  strings:
	$ChinaChopperASPX = {25 40 20 50 61 67 65 20 4C 61 6E 67 75 61 67 65 3D ?? 4A 73 63 72 69 70 74 ?? 25 3E 3C 25 65 76 61 6C 28 52 65 71 75 65 73 74 2E 49 74 65 6D 5B [1-100] 75 6E 73 61 66 65}
  condition:
	$ChinaChopperASPX
}

rule webshell_ChinaChopper_php
{
  meta:
		severity_score = 100
		confidence_score = 60
		exploitability_score = 80
		risk_score = 83
		risk_justification = "[Detect China Chopper PHP webshell] Web shell / backdoor signature -- indicates a deployed remote-code-execution capability if it matches. Confidence: regex/byte-pattern only (not individually inspected); medium confidence. Triggers whenever the shell is invoked via a normal HTTP request to the deployed file -- no special condition needed."
		finding_type = "malicious"
    author      = "Ryan Boyle randomrhythm@rhythmengineering.com"
    date        = "2020/10/29"
    description = "Detect China Chopper PHP webshell"
    reference1  = "https://www.fireeye.com/blog/threat-research/2013/08/breaking-down-the-china-chopper-web-shell-part-i.html"
    filetype    = "php"
  strings:
	$ChinaChopperPHP = {3C 3F 70 68 70 20 40 65 76 61 6C 28 24 5F 50 4F 53 54 5B ?? 70 61 73 73 77 6F 72 64 ?? 5D 29 3B 3F 3E}
  condition:
	$ChinaChopperPHP
}

