// AUTO-GENERATED by scripts/generate_scored_yara.py -- DO NOT EDIT BY HAND
// Source: yara_rules/Yara-Rules-Repo/webshells/Wshell_fire2013.yar (Yara-Rules project, https://github.com/Yara-Rules/rules)
// Risk scores per .claude/criterioPuntuacionReglas.md (risk = 0.45*severity + 0.30*confidence + 0.25*exploitability)
// Generated: 2026-08-31T08:26:58.778112
// Contains only the 1 rule(s) present in yara_scores_output/yara_rule_scores.json

rule fire2013 : webshell
{
    meta:
		severity_score = 100
		confidence_score = 100
		exploitability_score = 80
		risk_score = 95
		risk_justification = "[Catches a webshell] Web shell / backdoor signature -- indicates a deployed remote-code-execution capability if it matches. Confidence: requires 2 specific literal fragments to ALL match (min length 51); low FP risk. Triggers whenever the shell is invoked via a normal HTTP request to the deployed file -- no special condition needed."
		finding_type = "malicious"
        author      = "Vlad https://github.com/vlad-s"
        date        = "2016/07/18"
        description = "Catches a webshell"
    strings:
        $a = "eval(\"\\x65\\x76\\x61\\x6C\\x28\\x67\\x7A\\x69\\x6E\\x66\\x6C\\x61"
        $b = "yc0CJYb+O//Xgj9/y+U/dd//vkf'\\x29\\x29\\x29\\x3B\")"
    condition:
        all of them
}

