// AUTO-GENERATED by scripts/generate_scored_yara.py -- DO NOT EDIT BY HAND
// Source: yara_rules/Yara-Rules-Repo/webshells/WShell_PHP_in_images.yar (Yara-Rules project, https://github.com/Yara-Rules/rules)
// Risk scores per .claude/criterioPuntuacionReglas.md (risk = 0.45*severity + 0.30*confidence + 0.25*exploitability)
// Generated: 2026-08-28T10:49:10.219859
// Contains only the 1 rule(s) present in yara_scores_output/yara_rule_scores.json

rule php_in_image
{
    meta:
		severity_score = 100
		confidence_score = 60
		exploitability_score = 80
		risk_score = 83
		risk_justification = "[Finds image files w/ PHP code in images] Web shell / backdoor signature -- indicates a deployed remote-code-execution capability if it matches. Confidence: mixed specificity literal(s) (min length 5); moderate FP risk. Triggers whenever the shell is invoked via a normal HTTP request to the deployed file -- no special condition needed."
		finding_type = "malicious"
        author      = "Vlad https://github.com/vlad-s"
        date        = "2016/07/18"
        description = "Finds image files w/ PHP code in images"
    strings:
        $gif = /^GIF8[79]a/
        $jfif = { ff d8 ff e? 00 10 4a 46 49 46 }
        $png = { 89 50 4e 47 0d 0a 1a 0a }

        $php_tag = "<?php"
    condition:
        (($gif at 0) or
        ($jfif at 0) or
        ($png at 0)) and

        $php_tag
}

