// AUTO-GENERATED by scripts/generate_scored_yara.py -- DO NOT EDIT BY HAND
// Source: yara_rules/Yara-Rules-Repo/webshells/WShell_PHP_Anuna.yar (Yara-Rules project, https://github.com/Yara-Rules/rules)
// Risk scores per .claude/criterioPuntuacionReglas.md (risk = 0.45*severity + 0.30*confidence + 0.25*exploitability)
// Generated: 2026-08-28T10:49:10.217776
// Contains only the 1 rule(s) present in yara_scores_output/yara_rule_scores.json

rule php_anuna
{
    meta:
		severity_score = 100
		confidence_score = 60
		exploitability_score = 80
		risk_score = 83
		risk_justification = "[Catches a PHP Trojan] Web shell / backdoor signature -- indicates a deployed remote-code-execution capability if it matches. Confidence: regex/byte-pattern only (not individually inspected); medium confidence. Triggers whenever the shell is invoked via a normal HTTP request to the deployed file -- no special condition needed."
		finding_type = "malicious"
        author      = "Vlad https://github.com/vlad-s"
        date        = "2016/07/18"
        description = "Catches a PHP Trojan"
    strings:
        $a = /<\?php \$[a-z]+ = '/
        $b = /\$[a-z]+=explode\(chr\(\([0-9]+[-+][0-9]+\)\)/
        $c = /\$[a-z]+=\([0-9]+[-+][0-9]+\)/
        $d = /if \(!function_exists\('[a-z]+'\)\)/
    condition:
        all of them
}

