// AUTO-GENERATED by scripts/generate_scored_yara.py -- DO NOT EDIT BY HAND
// Source: yara_rules/Yara-Rules-Repo/packers/JJencode.yar (Yara-Rules project, https://github.com/Yara-Rules/rules)
// Risk scores per .claude/criterioPuntuacionReglas.md (risk = 0.45*severity + 0.30*confidence + 0.25*exploitability)
// Generated: 2026-08-28T10:49:09.619166
// Contains only the 1 rule(s) present in yara_scores_output/yara_rule_scores.json

rule jjEncode
{
   meta:
		severity_score = 75
		confidence_score = 100
		exploitability_score = 80
		risk_score = 84
		risk_justification = "Codigo JavaScript en formato jjencode -- sin motivo legitimo para que un desarrollador escriba o pegue codigo en este formato dentro de una fuente que se comitea a un repositorio (a diferencia de un minificador normal, que no produce esta forma); patron de regex muy especifico de esta sintaxis exacta, colision incidental practicamente imposible."
		finding_type = "malicious"
      description = "jjencode detection"
      ref = "http://blog.xanda.org/2015/06/10/yara-rule-for-jjencode/"
      author = "adnan.shukor@gmail.com"
      date = "10-June-2015"
      version = "1"
      impact = 3
      hide = false
   strings:
      $jjencode = /(\$|[\S]+)=~\[\]\;(\$|[\S]+)\=\{[\_]{3}\:[\+]{2}(\$|[\S]+)\,[\$]{4}\:\(\!\[\]\+["]{2}\)[\S]+/ fullword 
   condition:
      $jjencode
}

