// AUTO-GENERATED by scripts/generate_scored_yara.py -- DO NOT EDIT BY HAND
// Source: yara_rules/Yara-Rules-Repo/packers/tweetable-polyglot-png.yar (Yara-Rules project, https://github.com/Yara-Rules/rules)
// Risk scores per .claude/criterioPuntuacionReglas.md (risk = 0.45*severity + 0.30*confidence + 0.25*exploitability)
// Generated: 2026-08-28T10:49:10.183834
// Contains only the 1 rule(s) present in yara_scores_output/yara_rule_scores.json

rule TweetablePolyglotPng {
  meta:
		severity_score = 50
		confidence_score = 100
		exploitability_score = 80
		risk_score = 72
		risk_justification = "Detecta un fichero PNG/JPEG que es simultaneamente un ZIP valido (polyglot) -- tecnica deliberada de ocultacion de datos; el propio proyecto upstream declara un uso legitimo (embeber datos en imagenes 'tweeteables' sobreviviendo la recompresion de Twitter), pero la misma tecnica sirve como canal de exfiltracion encubierto."
		finding_type = "malicious"
		needs_review = true
		needs_review_reason = "detecta un fichero PNG/JPEG que es simultaneamente un ZIP valido (polyglot) -- tecnica deliberada de ocultacion de datos; el propio proyecto upstream declara un uso legitimo (embeber datos en imagenes 'tweeteables' sobreviviendo la recompresion de Twitter), pero la misma tecnica sirve como canal de exfiltracion encubierto"
    description = "tweetable-polyglot-png: https://github.com/DavidBuchanan314/tweetable-polyglot-png"
    author = "Manfred Kaiser"
  strings:
    $magic1 = { 50 4b 01 02 }
    $magic2 = { 50 4b 03 04 }
    $magic3 = { 50 4b 05 06 }

  condition:
    (
      uint32be(0) == 0x89504E47 or
      uint32be(0) == 0xFFD8FFE0
    ) and
    $magic1 and
    $magic2 and
    $magic3

}

